# embedded in-memory; close only when jvm exit; use MySQL mode
spring:
  datasource:
    url: jdbc:h2:mem:pokemon;DB_CLOSE_DELAY=-1;MODE=MySQL
    # embedded local file
    #spring.datasource.url=jdbc:h2:./pokemon
    driverClassName: org.h2.Driver
    #spring.datasource.username=sa
    #spring.datasource.password=password
    # sql schema
    schema: classpath:scripts/schema.sql
    data: classpath:scripts/data.sql
mybatis:
  configuration:
    map-underscore-to-camel-case: true
